In [4]:
import numpy as np
def Poisson(A):
    return 0

A=np.zeros([5,3])
A[0,1]=0.5**2
A[0,2]=1

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np

# Define the dimensions of the matrix
N = 9  # Total number of nodes (including boundary nodes)
interior_N = N - 2  # Number of interior nodes

# Define the coefficient values
a = -16  # Diagonal coefficient
b = 4   # Off-diagonal coefficient

# Create a zeros matrix for the A matrix
A = np.zeros((interior_N, interior_N))

# Fill in the interior nodes with the coefficient values
for i in range(interior_N):
    A[i, i] = a
    if i > 0:
        A[i, i-1] = b
    if i < interior_N - 1:
        A[i, i+1] = b

print(A)
print(b)
# # Define the boundary values for the problem
# u_0 = np.array([0, 1, 0, 1, 4, 1, 9, 4, 16])  # Values along the left and bottom boundaries
# u_1 = np.array([1, 0, 1, 0, 9, 4, 16, 9, 0])  # Values along the right and top boundaries

# # Solve the system of equations using the boundary values
# u_interior = np.linalg.solve(A, -b * np.concatenate((u_0[1:-1], u_1[1:-1])))

# # Combine the interior and boundary values into a single solution vector
# u = np.concatenate(([u_0[0]], u_interior, [u_1[0]]))

# # Print the solution vector
# print(u)


[[-16.   4.   0.   0.   0.   0.   0.]
 [  4. -16.   4.   0.   0.   0.   0.]
 [  0.   4. -16.   4.   0.   0.   0.]
 [  0.   0.   4. -16.   4.   0.   0.]
 [  0.   0.   0.   4. -16.   4.   0.]
 [  0.   0.   0.   0.   4. -16.   4.]
 [  0.   0.   0.   0.   0.   4. -16.]]
4
[0.       0.015625 0.0625   0.140625 0.25     0.390625 0.5625   0.765625
 1.       0.0625   1.       1.       1.       1.       1.       1.
 1.       0.5625   0.25     1.       1.       1.       1.       1.
 1.       1.       0.25     0.5625   1.       1.       1.       1.
 1.       1.       1.       0.0625   1.       1.       1.       1.
 1.       1.       1.       1.       0.       1.5625   1.       1.
 1.       1.       1.       1.       1.       0.0625   2.25     1.
 1.       1.       1.       1.       1.       1.       0.25     3.0625
 1.       1.       1.       1.       1.       1.       1.       0.5625
 0.       0.015625 0.0625   0.140625 0.25     0.390625 0.5625   0.765625
 1.      ]


In [1]:
import numpy as np

f=lambda x:np.sin(np.pi*x)

def CN(L,T,alp,h,k):
    m=int(L/h)
    n=int(T/h)
    lam=alpha**2*k/h**2
    w=np.zeros([m+1,N+1])
    xs=np.array([i+h for i in range(m+1)])
    w[:,0]=f(xs)
    l=np.zeros(m)
    u=np.zeros(n)
    l[1]=1+lam
    u[1]=-lam/(2*l[1])
    for i in range(2,m-1):
        l[i]=1+lam+lam*u[i-1]/2
        u[i]=-lam/(2*l[i])
    
    l[m-1]=1+lam+lam*u[m-2]/2
    
    z=np.zeros(m)
    
    for j in range(1,N+1):
        t=j*k
        z[1]=((1-lam)*w[1,j-1]+lam/2*w[2,j-1])/l[1]
        
        for i in range(2,m):
            z[i]=((1-lam)*w[i,j-1]+lam/2*(w[i+1,j-1]+w[i-1,j-1]+z[i-1]))/l[i]
        w[m-1,j]=z[m-1]
        for i in range(m-2,0,-1):
            w[i,j]=z[i]-u[i]*w[i+1,j-1]
    return w

