### 1. Use the Gaussian elimination algorithm to solve the following linear systems, if possible.

In [5]:
import numpy as np

def GE(A):
    n=A.shape[0]
    x=np.zeros(n)
    for i in range(n):
        p=i
        while(A[p,i]==0):
            p+=1
        if(p==n):
            print("No unique solution1")
            return
        if (p!=i):
            A[[i,p],:]=A[[p,i],:]
        for j in range(i+1,n):
            m=A[j,i]/A[i,i]
            A[j,:]=A[j,:]-m*A[i,:]
        if(A[n-1,n-1]==0):
            print("No unique solution2")
            return
    x[n-1]=A[n-1,n]/A[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i]=(A[i,n]-sum(A[i,(i+1):n]*x[(i+1):n]))/A[i,i]
    return(x)



a=np.array([[1,1,-1,1],[1,1,4,2],[2,-1,2,3]])
x=(GE(a))
print(x)
b=np.array([[2,-3,2,5],[-4,2,-6,14],[2,2,4,8]])

x=(GE(b))
print(x)



[ 1.26666667 -0.06666667  0.2       ]
No unique solution2
None


### 2. Repeat (1) using the partial pivoting algorithm. Note any differences in the results.

In [2]:
import numpy as np

def GE(A):
    n=A.shape[0]
    x=np.zeros(n)
    nrow=np.arange(n)
    for i in range(n):
        p=i
        nrow[i]=i
        while(A[p,i]==0):
            p+=1
        if(p==n):
            print("No unique solution1")
            return
        if (nrow[p]!=nrow[i]):
            A[[i,p],:]=A[[p,i],:]
        for j in range(i+1,n):
            m=A[nrow[j],i]/A[nrow[i],i]
            A[nrow[j],:]=A[nrow[j],:]-m*A[nrow[i],:]
        if(A[nrow[n-1],n-1]==0):
            print("No unique solution2")
            return
    x[n-1] = A[nrow[n-1], n] / A[nrow[n-1], n-1]
    for i in range(n-2, -1, -1):
        x[i] = (A[nrow[i], n] - np.sum(A[nrow[i], (i+1):n] * x[(i+1):n])) / A[nrow[i], i]
    return x

a=np.array([[1,1,-1,1],[1,1,4,2],[2,-1,2,3]])
x=(GE(a))
print(x)
b=np.array([[2,-3,2,5],[-4,2,-6,14],[2,2,4,8]])
x=(GE(b))
print(x)

[ 1.26666667 -0.06666667  0.2       ]
No unique solution2
None


### 3. Repeat (1) using the scaled partial pivoting algorithm. Note any differences in the results.

In [7]:
def GE(A,b):
    n=A.shape[0]
    A = A.astype(float) 
    b = b.astype(float)
    x=np.zeros(n)
    s=np.zeros(n)
    for i in range(n):
        s[i]=np.max(abs(A[:,i]))
        if(s[i]==0):
            print("No unique solution1")
            return
        for j in range(n-1):
            mx_row_idx = np.argmax(abs(A[j:, j])/s[j:]) + j
            if (mx_row_idx!=j):
                A[[j,mx_row_idx]]=A[[mx_row_idx,j]]
                b[[j,mx_row_idx]]=b[[mx_row_idx,j]]
                s[[j,mx_row_idx]]=s[[mx_row_idx,j]]
        for j in range(i+1, n):
            factor = A[j, i] / A[i, i]
            A[j, i+1:] -= factor * A[i, i+1:]
            b[j] -= factor * b[i]
        if(A[n-1,n-1]==0):
            print("No unique solution2")
            return
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x

a=np.array([[1,1,-1],[1,1,4],[2,-1,2]])
b=np.array([1,2,3])
x=(GE(a,b))
print(x)
a1=np.array([[2,-3,2],[-4,2,-6],[2,2,4]])
b2=np.array([5,14,8])
x=(GE(a1,b2))
print(x)
print("Ignore Error, there is no divide by 0 because this code is supposed to return null if s is 0")

[ 1.26666667 -0.06666667  0.2       ]
[109.  27. -66.]
Ignore Error, there is no divide by 0 because this code is supposed to return null if s is 0


/var/folders/0_/31jtytdd6cnfrpb7n67kffhw0000gn/T/ipykernel_1103/532997873.py:13: RuntimeWarning: divide by zero encountered in true_divide
  mx_row_idx = np.argmax(abs(A[j:, j])/s[j:]) + j


### 4. Use the Jacobi method to solve the following linear systems with T OL = 10−3 in the l∞ norm. Use x(0) = 0.

In [8]:
import numpy as np
import pandas as pd

# Jacobi Method
def Jacobi(A, b, x0, TOL, Nmax):
    k = 1
    n = len(A)
    x = np.zeros(n)
    x0_old = np.copy(x0)
    while k <= Nmax:
        for i in range(n):
            x[i] = 1/A[i,i]*(-np.dot(np.concatenate((A[i,0:i],A[i,i+1:])),np.concatenate((x0_old[0:i],x0_old[i+1:])))+b[i])
        if (max(abs(x-x0_old))<TOL):
            return x
        else:
            k += 1
            x0_old = np.copy(x)
    print("Exceeded Nmax")
    
a1=np.array([[3,-1,1],[3,6,2],[3,3,7]])
b1=np.array([1,0,4])
a2=np.array([[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]])
b2=np.array([6,25,-11,-11])
p0=[0,0,0]
p01=[0,0,0,0]
print(Jacobi(a1,b1,p0,0.001,1000))
print(Jacobi(a2,b2,p01,0.001,1000))

[ 0.03510079 -0.23663751  0.65812732]
[-0.79710581  2.79517067 -0.25939578 -2.25179299]


### 5. Repeat problem 1 using the Gauss-Seidel method.

In [3]:
def GS(A,b, TOL, Nmax):
    n = len(A)
    x = np.zeros(n)
    x0 = np.copy(x)
    for k in range(Nmax):
        for i in range(n):
            x[i]=1/A[i,i]*(-np.dot(A[i,:i],x[:i])-np.dot(A[i,i+1:],x0[i+1:])+b[i])
        if np.linalg.norm(x-x0,np.inf)<TOL:
            return x 
    else:
        x0 = np.copy(x)
    print("Exceeded Nmax")
a=np.array([[1,1,-1],[1,1,4],[2,-1,2]])
b=np.array([1,2,3])
a1=np.array([[2,-3,2],[-4,2,-6],[2,2,4]])
b1=np.array([5,14,8])
print(GS(a,b,10**-3,1000))
print(GS(a1,b1,10**-3,1000))

Exceeded Nmax
None
Exceeded Nmax
None


### 6. Repeat problem 1 using the SOR method with ω = 1.2.

In [5]:
def SOR(A, b, w, TOL, Nmax):
    n=len(A)
    k=1
    x = np.zeros(n)
    x0 = np.copy(x)
    while k<=Nmax:
        for i in range(n):
            x[i]=(1-w)*x0[i]+(1/A[i,i])*(w*(-sum(A[i,j]*x[j] for j in range(i-1))-sum(A[i,j]*x0[j] for j in range(i+1,n))+b[i]))
            #print(x[i])
            if all(abs(x[i]-x0[i]) < TOL for i in range(n)):
                return x 
            else:
                x0 = np.copy(x) 
        k+=1
    print("Exceeded Max")
        
a=np.array([[1,1,-1],[1,1,4],[2,-1,2]])
b=np.array([1,2,3])
a1=np.array([[2,-3,2],[-4,2,-6],[2,2,4]])
b1=np.array([5,14,8])
TOL = 10**(-3)
Nmax=30
print(SOR(a,b,1.2,TOL,Nmax))
print(SOR(a1,b1,1.2,TOL,Nmax))

#Chat GPT answer that basically gave me the same output:
# def SOR(A, b, w, TOL, Nmax):
#     n = len(A)
#     k = 1
#     x = np.zeros(n)
#     x0 = np.copy(x)
#     while k <= Nmax:
#         for i in range(n):
#             x[i] = (1-w)*x0[i] + (w/A[i,i]) * (-sum(A[i,j]*x[j] for j in range(i)) - sum(A[i,j]*x[j] for j in range(i+1, n)) + b[i])
#             print(x[i])
#         if all(abs(x - x0) < TOL):
#             return x
#         else:
#             x0 = np.copy(x)
#         k += 1
#     print("Exceeded Max")
    
# a = np.array([[1, 1, -1], [1, 1, 4], [2, -1, 2]])
# b = np.array([1, 2, 3])
# a1 = np.array([[2, -3, 2], [-4, 2, -6], [2, 2, 4]])
# b1 = np.array([5, 14, 8])
# TOL = 10 ** (-3)
# Nmax = 30
# print(SOR(a, b, 1.2, TOL, Nmax))
# print(SOR(a1, b1, 1.2, TOL, Nmax))

Exceeded Max
None
Exceeded Max
None
